# Generated by Django 6.0 on 2025-12-07 20:18

import django.db.models.deletion
import django_ckeditor_5.fields
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='کلید')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_own', models.BooleanField(default=False, help_text='is brand is for this company ?')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_logo', to='core_app.image')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_images', to='core_app.image')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.productcategory', verbose_name='زیر دسته بندی')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=256, verbose_name='اسلاگ')),
                ('commercial_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='کد تجاری')),
                ('sku', models.CharField(verbose_name='شناسه محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='قیمت تخفیف')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه محصول')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیح در مورد  محصول')),
                ('is_available', models.BooleanField(default=True, verbose_name='محصول در دسترس هست')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='موجودی')),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True, verbose_name='متا تایتل')),
                ('meta_description', models.CharField(blank=True, max_length=320, null=True, verbose_name='متا دیسکریپشن')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brands', to='product.brand', verbose_name='برند')),
                ('similar_products', models.ManyToManyField(blank=True, related_name='related_to', to='product.product', verbose_name='محصولات مشابه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productcategory', verbose_name='دسته بندی')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=512)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='product.attribute', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_features', to='product.product')),
            ],
            options={
                'db_table': 'product_feature',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='core_app.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='product.product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(verbose_name='نمرد دهی')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_parents', to='product.productreview', verbose_name='کامنت والد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='product.product', verbose_name='محصول')),
            ],
            options={
                'db_table': 'product_review',
                'ordering': ('id',),
            },
        ),
    ]
