# Generated by Django 6.0 on 2025-12-04 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='product/country/')),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True, max_length=256)),
                ('image', models.ImageField(upload_to='media/product/product-category/')),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_own', models.BooleanField(default=False, help_text='is brand is for this company ?')),
                ('logo', models.ImageField(upload_to='product/brand/')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True, max_length=256)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.country')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True, max_length=256)),
                ('technical_code', models.CharField(blank=True, max_length=256, null=True)),
                ('commercial_code', models.CharField(blank=True, max_length=256, null=True)),
                ('main_image', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('short_description', models.TextField(blank=True, null=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.brand')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.country')),
                ('similar_products', models.ManyToManyField(to='product.product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productcategory')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=512)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_features', to='product.product')),
            ],
            options={
                'db_table': 'product_feature',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='product.product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
    ]
