# Generated by Django 6.0 on 2025-12-07 20:26

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='parent',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_parents', to='product.productreview', verbose_name='کامنت والد'),
        ),
    ]
