# Generated by Django 6.0 on 2025-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='date',
            new_name='created_at',
        ),
    ]
