# Generated by Django 6.0 on 2025-12-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_date_country_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(null=True, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commercial_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='کد تجاری'),
        ),
    ]
