# Generated by Django 6.0 on 2025-12-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_image_height_image_size_image_width'),
        ('product', '0004_product_sku_alter_product_commercial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_logo', to='core_app.image'),
        ),
    ]
