# Generated by Django 6.0 on 2025-12-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productreview_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نمرد دهی'),
        ),
    ]
