# Generated by Django 6.0 on 2025-12-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
