# Generated by Django 6.0 on 2025-12-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_image_height_image_size_image_width'),
        ('product', '0007_brand_created_at_brand_is_active_brand_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_images', to='core_app.image', verbose_name='عکس فلگ'),
        ),
    ]
