# Generated by Django 6.0 on 2025-12-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
    ]
