# Generated by Django 6.0 on 2025-12-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
    ]
