# Generated by Django 6.0 on 2025-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیح در مورد  محصول'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
