# Generated by Django 6.0 on 2025-12-07 19:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_description_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='توضیح در مورد  محصول'),
        ),
    ]
