# Generated by Django 6.0 on 2025-12-07 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfeature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
