# Generated by Django 6.0 on 2025-12-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_productfeature_created_at_productfeature_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='کلید')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='product.attribute', verbose_name='ویژگی'),
        ),
    ]
