# Generated by Django 6.0 on 2025-12-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Upload the original image file.', null=True, upload_to='images/%Y/%m/%d/', verbose_name='عکس')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='حجم عکس')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='ارتفاع')),
                ('image_id_ba_salam', models.BigIntegerField(blank=True, editable=False, help_text='ID of the image in external storage', null=True, verbose_name='ای دی عکس اپلود شده درون با سلام')),
            ],
            options={
                'db_table': 'core_app_image',
            },
        ),
        migrations.CreateModel(
            name='PublicNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن نوتیفکیشن')),
            ],
            options={
                'db_table': 'public_notification',
            },
        ),
    ]
