# Generated by Django 6.0 on 2025-12-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicnotification',
            options={'ordering': ('id',)},
        ),
    ]
