# Generated by Django 6.0 on 2025-12-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date',
            new_name='created_at',
        ),
    ]
