# Generated by Django 6.0 on 2025-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_rename_date_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='ارتفاع'),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='حجم عکس'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='عرض'),
        ),
    ]
