# Generated by Django 6.0 on 2025-12-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('instagram_page', models.CharField(blank=True, max_length=128, null=True)),
                ('telegram_channel', models.CharField(blank=True, max_length=128, null=True)),
                ('whatsapp_support', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='SliderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'slider_config',
            },
        ),
        migrations.CreateModel(
            name='GrouLinkFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_links', to='template.footer')),
            ],
            options={
                'db_table': 'grou_link_footer',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('group_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='template.groulinkfooter')),
            ],
            options={
                'db_table': 'footer_link',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template/footer/license/')),
                ('url', models.CharField(max_length=256)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='template.footer')),
            ],
            options={
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/template/slider/slides')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='template.sliderconfig')),
            ],
            options={
                'db_table': 'slider_image',
            },
        ),
        migrations.CreateModel(
            name='SlideBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/template/slider/slide-box')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(default='/', max_length=256)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='template.sliderconfig')),
            ],
            options={
                'db_table': 'slider_box',
            },
        ),
    ]
