# Generated by Django 6.0 on 2025-12-06 19:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slidebox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slidebox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slidebox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slideimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sliderconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram_page',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='slidebox',
            name='image_url',
            field=models.ImageField(upload_to='media/template/slider/slide-box', verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='slidebox',
            name='link',
            field=models.CharField(default='/', max_length=256, verbose_name='لینک عکس'),
        ),
        migrations.AlterField(
            model_name='slidebox',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='template.sliderconfig', verbose_name='اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidebox',
            name='title',
            field=models.CharField(max_length=256, verbose_name='عنوان عکس'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='image_url',
            field=models.ImageField(upload_to='media/template/slider/slides', verbose_name='لینک عکس'),
        ),
        migrations.AlterField(
            model_name='slideimage',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='template.sliderconfig', verbose_name='اسلایدر'),
        ),
        migrations.AlterField(
            model_name='sliderconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
