# Generated by Django 6.0 on 2025-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_footer_created_at_footer_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, verbose_name='عنوان هدر')),
            ],
            options={
                'db_table': 'header_site',
            },
        ),
    ]
