# Generated by Django 6.0 on 2025-12-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_publicnotification'),
        ('template', '0003_headersite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidebox',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slidebox',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slider_box_images', to='core_app.image', verbose_name='عکس باکس'),
        ),
    ]
