# Generated by Django 6.0 on 2025-12-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_publicnotification'),
        ('template', '0004_remove_slidebox_image_url_slidebox_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slideimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slider_images', to='core_app.image', verbose_name='عکس اسلایدر'),
        ),
    ]
